In [ ]:
# L2_cal.py

import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('./3A/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)


# 3.A: liste todos os parametros obtidos, colocando-os nas formas de vetores e matrizes (Matriz K, matriz R, vetor t, vetor dos coeficientes de distorção)

Do código 3A executado,foram obtido os seguintes parâmetros:
```python
Camera matrix : 
[[536.07345302   0.         342.37047252]
 [  0.         536.01636339 235.53687724]
 [  0.           0.           1.        ]]

dist : 
[[-0.26509044 -0.04674186  0.00183301 -0.00031469  0.25231153]]

rvecs : 
(array([[-0.08398729],
       [ 0.34802798],
       [-1.54244125]]), array([[-0.22584614],
       [ 1.0155115 ],
       [-2.79470623]]), array([[-0.34698232],
       [-0.06738512],
       [-1.20088998]]), array([[-0.27527313],
       [ 0.1012335 ],
       [-1.56296568]]), array([[-0.4735952 ],
       [ 0.08970834],
       [-0.22605981]]), array([[0.06525918],
       [0.44701842],
       [0.10800013]]), array([[-0.10141628],
       [ 0.32034812],
       [ 0.3147293 ]]), array([[-0.35339067],
       [ 0.24071863],
       [ 0.20970027]]), array([[ 0.48287277],
       [-0.17037077],
       [-1.40740327]]), array([[ 0.05280128],
       [-0.60171832],
       [-0.18453815]]), array([[-0.37463355],
       [ 0.06982818],
       [-0.01937111]]), array([[ 0.49542337],
       [ 0.11948808],
       [-0.29675958]]), array([[ 0.19721096],
       [-0.42009963],
       [-0.1949708 ]]))

tvecs : 
(array([[-2.96218416],
       [ 0.57158931],
       [16.83013775]]), array([[ 2.5339942 ],
       [ 4.31999127],
       [13.71919122]]), array([[-3.42743599],
       [ 0.4873819 ],
       [11.56153507]]), array([[-3.99388097],
       [ 2.27704342],
       [12.68878108]]), array([[-2.51791825],
       [-3.43069106],
       [12.85702135]]), array([[ 2.2074184 ],
       [-3.21446614],
       [15.60125393]]), array([[-3.72585433],
       [-4.31084851],
       [17.20439704]]), array([[-1.59004094],
       [-4.31771235],
       [14.01040668]]), array([[-3.50264636],
       [ 1.61595403],
       [11.97222152]]), array([[-2.16838793],
       [-3.50011196],
       [10.73694991]]), array([[-2.9584873 ],
       [-3.94417974],
       [13.21423743]]), array([[-3.40557513],
       [-2.41042316],
       [12.58706805]]), array([[-2.67642941],
       [-3.18945603],
       [10.58262241]]))
```

---

## Matriz K:
```python 
[[536.07     0          342.37   ]   
[  0       536.02      235.53   ]
[  0         0            1     ]]
```

## Matrizes de rotação:
```python
Matriz de Rotação 1:
[[-0.00980077  0.96222056  0.27209471]
 [-0.98583134  0.03626968 -0.16377143]
 [-0.16745303 -0.26984458  0.94823171]]

Matriz de Rotação 2:
[[-0.9759021   0.0976268   0.19515146]
 [-0.20013528 -0.75683746 -0.6222081 ]
 [ 0.08695375 -0.64627089  0.75813784]]

Matriz de Rotação 3:
[[ 0.36632319  0.92116245  0.13140422]
 [-0.90067926  0.31557571  0.298645  ]
 [ 0.23363258 -0.22775364  0.94527461]]

Matriz de Rotação 4:
[[ 0.01109733  0.971425    0.23708715]
 [-0.99389249 -0.01531807  0.10928435]
 [ 0.10979327 -0.23685191  0.96532202]]

Matriz de Rotação 5:
[[ 0.9711167   0.19478528  0.13780803]
 [-0.23627664  0.86552416  0.44163479]
 [-0.03325222 -0.46143974  0.88654817]]

Matriz de Rotação 6:
[[ 0.89614282 -0.08983267  0.43457812]
 [ 0.118484    0.99218072 -0.03922963]
 [-0.42765592  0.08664591  0.89977936]]

Matriz de Rotação 7:
[[ 0.90092991 -0.31968741  0.29347106]
 [ 0.28776872  0.94628897  0.14739861]
 [-0.3248299  -0.04834402  0.94453607]]

Matriz de Rotação 8:
[[ 0.94999608 -0.24359885  0.1953639 ]
 [ 0.16012684  0.91715415  0.36494884]
 [-0.26807993 -0.31541696  0.91029956]]

Matriz de Rotação 9:
[[ 0.16943175  0.90322679 -0.39430222]
 [-0.97122197  0.08506949 -0.22246589]
 [-0.16739407  0.42064776  0.89164717]]

Matriz de Rotação 10:
[[ 0.80843739  0.15714697 -0.56721584]
 [-0.18787626  0.98218312  0.00433858]
 [ 0.55779162  0.10305892  0.82355775]]

Matriz de Rotação 11:
[[ 0.9974061   0.00598239  0.07173068]
 [-0.0318265   0.93048684  0.36494015]
 [-0.06456124 -0.36627646  0.92826365]]

Matriz de Rotação 12:
[[ 0.95029417  0.30860531  0.04127659]
 [-0.25110403  0.83802199 -0.48442327]
 [-0.18408629  0.44997989  0.87385945]]

Matriz de Rotação 13:
[[ 0.89499694  0.14628379 -0.42140423]
 [-0.22739734  0.96235225 -0.14889123]
 [ 0.38375894  0.2290834   0.89456687]]
```

## Vetores de translação
```python
1.  [−2.96218416,0.57158931,16.83013775]
2.  [2.5339942,4.31999127,13.71919122]
3.  [−3.42743599,0.4873819,11.56153507]
4.  [−3.99388097,2.27704342,12.68878108]
5.  [−2.51791825,−3.43069106,12.85702135]
6.  [2.2074184,−3.21446614,15.60125393]
7.  [−3.72585433,−4.31084851,17.20439704]
8.  [−1.59004094,−4.31771235,14.01040668]
9.  [−3.50264636,1.61595403,11.97222152]
10. [−2.16838793,−3.50011196,10.73694991]
11. [−2.9584873,−3.94417974,13.21423743]
12. [−3.40557513,−2.41042316,12.58706805]
13. [−2.67642941,−3.18945603,10.58262241]
```

# Vetor de distorção:
```python
[-0.26509044 -0.04674186  0.00183301 -0.00031469  0.25231153]
```

In [ ]:
# L2_chess.py

import numpy as np
import cv2 as cv

cap = cv.VideoCapture(0)

if not cap.isOpened():
    print("Cannot open camera")
    exit()
    
i = 0
    
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    
    # Display the resulting frame
    cv.imshow('frame', frame)

    # Save on "s" key or exit on "q"
    k = cv.waitKey(1) 
    if  k == ord('s'):
        cv.imwrite(r"3B/samir"+str(i)+".jpg",frame)
        i = i + 1
        print("samir"+str(i), i)
    elif k == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv.destroyAllWindows()


In [ ]:
# L2_cal.py

import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,8)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('./3B/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

# 3.B: Liste todos os parametros obtidos, colocando-os nas formas de vetores e matrizes.

Do código 3B executado,foram obtido os seguintes parâmetros:
```python
Camera matrix : 
[[681.97214459   0.         328.63122084]
 [  0.         682.34022002 237.00506918]
 [  0.           0.           1.        ]]

dist : 
[[ 7.73727877e-02 -1.09277605e+00  7.84512238e-03  6.38718489e-05
   5.19749735e+00]]

rvecs : 
(array([[-0.12837455],
       [-0.0957297 ],
       [-1.54430751]]), array([[-0.14538027],
       [ 0.03122607],
       [ 0.00685209]]), array([[-0.21356298],
       [-0.06773979],
       [-1.13632952]]), array([[-0.20285087],
       [-0.15603571],
       [-1.40256942]]), array([[-0.44638972],
       [-0.26216524],
       [ 1.45164909]]), array([[-0.52695281],
       [ 0.18012537],
       [ 0.55071221]]), array([[-1.13605716],
       [ 0.16932604],
       [-0.00797051]]), array([[-0.22790417],
       [ 0.20765687],
       [ 0.87021978]]), array([[-0.26567918],
       [ 0.16070346],
       [ 0.28863916]]), array([[-0.15987166],
       [-0.04319511],
       [-0.30841976]]), array([[-0.23597121],
       [ 0.02974252],
       [-0.73612446]]), array([[-0.04788327],
       [ 0.12911439],
       [ 1.43673459]]))

tvecs : 
(array([[-3.3946943 ],
       [ 1.9748252 ],
       [11.17949976]]), array([[-1.86670823],
       [-3.68315277],
       [13.92822951]]), array([[-4.73861702],
       [ 1.00754953],
       [15.69476595]]), array([[-4.28859287],
       [ 2.03152445],
       [14.89176105]]), array([[ 2.96723107],
       [-2.73650833],
       [13.93190295]]), array([[-0.28415668],
       [-4.66450735],
       [15.80908521]]), array([[-2.29173779],
       [-0.75803301],
       [15.39315768]]), array([[ 1.51695388],
       [-4.22556745],
       [18.17545571]]), array([[-1.35551933],
       [-4.34227593],
       [18.42059263]]), array([[-4.89996914],
       [-2.38377024],
       [15.98243201]]), array([[-4.61906872],
       [-0.74179852],
       [17.44198903]]), array([[ 3.16100216],
       [-2.72788676],
       [15.17414217]]))
```

---

## Matriz K:
```python 
[[681.97214459   0.         328.63122084]
 [  0.         682.34022002 237.00506918]
 [  0.           0.           1.        ]]
```

## Matrizes de rotação:
```python
Matriz de Rotação 1:
[[ 0.0249194   0.99950703  0.0190979 ]
 [-0.98949636  0.0219397   0.14288318]
 [ 0.14239374 -0.02245786  0.98955529]]

Matriz de Rotação 2:
[[ 0.99948993 -0.00909245  0.03061372]
 [ 0.00456117  0.98942835  0.14495077]
 [-0.03160804 -0.1447372   0.98896515]]

Matriz de Rotação 3:
[[ 0.42134967  0.9052418   0.05478816]
 [-0.89232167  0.40303211  0.20329082]
 [ 0.16194596 -0.13454518  0.97758432]]

Matriz de Rotação 4:
[[ 0.16187823  0.98674442  0.01144069]
 [-0.96010362  0.15480757  0.23288548]
 [ 0.22802734 -0.04868334  0.97243687]]

Matriz de Rotação 5:
[[ 0.11100552 -0.8936754  -0.43476666]
 [ 0.98929708  0.0576772   0.13403223]
 [-0.09470518 -0.4449917   0.89051295]]

Matriz de Rotação 6:
[[ 0.84054271 -0.54119398  0.02443435]
 [ 0.45103021  0.72406675  0.52182286]
 [-0.30009949 -0.42759376  0.85270386]]

Matriz de Rotação 7:
[[ 0.98714437 -0.0797315   0.1385239 ]
 [-0.0923913   0.42256084  0.9016131 ]
 [-0.13042174 -0.9028207   0.40976206]]

Matriz de Rotação 8:
[[ 0.62742845 -0.7737906   0.08707263]
 [ 0.72973216  0.62332342  0.28099624]
 [-0.27170666 -0.11276533  0.95575074]]

Matriz de Rotação 9:
[[ 0.94624332 -0.30110061  0.11816095]
 [ 0.25904068  0.92419658  0.28063963]
 [-0.19370471 -0.23494488  0.95251215]]

Matriz de Rotação 10:
[[ 0.95199894  0.30557662 -0.01791521]
 [-0.29874118  0.94027286  0.16321966]
 [ 0.0667213  -0.15003293  0.98642708]]

Matriz de Rotação 11:
[[ 0.74188493  0.66153091  0.1094697 ]
 [-0.66820618  0.71582546  0.20271756]
 [ 0.05574273 -0.22354143  0.97309916]]

Matriz de Rotação 12:
[[ 0.1280931  -0.9899513   0.05990473]
 [ 0.98477032  0.13411749  0.11063415]
 [-0.1175567   0.04482093  0.99205419]]
```

## Vetores de translação
```python
1.  [−3.3946943,1.9748252,11.17949976]
2.  [−1.86670823,−3.68315277,13.92822951]
3.  [−4.73861702,1.00754953,15.69476595]
4.  [−4.28859287,2.03152445,14.89176105]
5.  [2.96723107,−2.73650833,13.93190295]
6.  [−0.28415668,−4.66450735,15.80908521]
7.  [−2.29173779,−0.75803301,15.39315768]
8.  [1.51695388,−4.22556745,18.17545571]
9.  [−1.35551933,−4.34227593,18.42059263]
10. [−4.89996914,−2.38377024,15.98243201]
11. [−4.61906872,−0.74179852,17.44198903]
12. [3.16100216,−2.72788676,15.17414217]
```

# Vetor de distorção:
```python
[ 7.73727877e-02 -1.09277605e+00  7.84512238e-03  6.38718489e-05 5.19749735e+00]
```

# 3.C:  Realize a calibração de uma outra câmera pessoal. Liste todos os parametros obtidos, colocando-os nas formas de matrizes e vetores.

Do código 3C executado,foram obtido os seguintes parâmetros. Em comparação com  o equipamento do laboratório, a câmera pessoal apresentou valores de calibração em escala bem maior:

```python
Camera matrix : 
[[1.13511501e+03 0.00000000e+00 7.77037877e+02]
 [0.00000000e+00 1.13837129e+03 6.33562127e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

dist : 
[[ 0.07726933 -0.43758116  0.00139022  0.00357039  0.58434254]]

rvecs : 
(array([[-0.01173509],
       [ 0.03004585],
       [ 0.12983663]]), array([[-0.01148928],
       [ 0.02584389],
       [-0.61279625]]), array([[-0.14890958],
       [ 0.00431857],
       [-1.39434729]]), array([[-0.08279921],
       [-0.12226273],
       [-1.27395249]]), array([[-0.01742351],
       [ 0.11871405],
       [ 1.20276048]]), array([[-0.08593405],
       [ 0.02045509],
       [ 0.06374097]]), array([[0.01917521],
       [0.01267349],
       [0.76349495]]), array([[-0.10707673],
       [ 0.03379654],
       [ 0.7005548 ]]), array([[-0.13441484],
       [ 0.00142601],
       [-0.7024908 ]]), array([[-0.07437629],
       [-0.18120508],
       [-1.3923437 ]]), array([[-0.05354585],
       [-0.12995032],
       [-1.03465398]]), array([[-0.02062632],
       [-0.00539937],
       [-0.4111568 ]]), array([[-0.11921491],
       [-0.0146227 ],
       [ 1.18482729]]), array([[-0.06781643],
       [ 0.00661503],
       [ 0.8551715 ]]), array([[-0.15232861],
       [-0.01373962],
       [-0.76108507]]), array([[-0.06017196],
       [-0.0401058 ],
       [-1.56975755]]), array([[-0.07183315],
       [-0.09131127],
       [ 1.58480133]]))

tvecs : 
(array([[-0.51390472],
       [-3.61087759],
       [11.98349545]]), array([[-2.23785966],
       [-0.91020112],
       [11.98254531]]), array([[-2.74120302],
       [ 1.27218519],
       [12.23502419]]), array([[-1.8170356 ],
       [ 0.37274676],
       [11.85786959]]), array([[ 2.41180475],
       [-4.171764  ],
       [11.90631951]]), array([[-1.19673582],
       [-4.17106584],
       [12.61140685]]), array([[ 1.85675187],
       [-4.07619415],
       [11.83062353]]), array([[ 1.69711179],
       [-4.28347655],
       [12.38334676]]), array([[-3.36115948],
       [-1.84006522],
       [12.48795394]]), array([[-3.01652001],
       [ 0.72076773],
       [12.66147845]]), array([[-3.45083683],
       [-0.84847687],
       [12.65008913]]), array([[-2.64590217],
       [-2.58070564],
       [12.8343403 ]]), array([[ 3.17631449],
       [-4.17250226],
       [11.66669065]]), array([[ 1.28179035],
       [-4.54498845],
       [10.81781082]]), array([[-4.32220073],
       [-1.54420476],
       [11.41354967]]), array([[-3.53420462],
       [ 2.45834165],
       [ 8.56083308]]), array([[ 2.1943884 ],
       [ 0.49049849],
       [12.30880216]]))
```

---

## Matriz K:
```python 
[[1135  0    777  ]
 [ 0   1138  633.5]
 [ 0    0    1    ]]

```

## Matrizes de rotação:
```python
Matriz de Rotação 1:
[[ 0.99113309 -0.12962571  0.02919562]
 [ 0.12927364  0.99151504  0.01364773]
 [-0.03071699 -0.0097525   0.99948054]]

Matriz de Rotação 2:
[[ 0.81773153  0.57493463  0.02766447]
 [-0.57522236  0.81799118  0.00310882]
 [-0.02084192 -0.0184554   0.99961243]]

Matriz de Rotação 3:
[[ 0.17710234  0.97998414  0.09091671]
 [-0.98052851  0.167725    0.102138  ]
 [ 0.08484462 -0.10723531  0.99060687]]

Matriz de Rotação 4:
[[ 0.28732004  0.9567533  -0.04550086]
 [-0.94794369  0.29084121  0.12966942]
 [ 0.13729517  0.00587563  0.99051275]]

Matriz de Rotação 5:
[[ 0.35434108 -0.93146249  0.08258339]
 [ 0.92963396  0.36043619  0.07659272]
 [-0.10110929  0.04963238  0.99363652]]

Matriz de Rotação 6:
[[ 0.99776155 -0.06449301  0.01767861]
 [ 0.06273696  0.99428187  0.08641547]
 [-0.02315071 -0.08511293  0.99610232]]

Matriz de Rotação 7:
[[ 0.7223597  -0.6912714   0.01844758]
 [ 0.69150283  0.72226111 -0.01275685]
 [-0.00450552  0.02197159  0.99974844]]

Matriz de Rotação 8:
[[ 0.7641865  -0.64497652 -0.00492776]
 [ 0.64150698  0.75923781  0.10966651]
 [-0.06699098 -0.08696686  0.99395622]]

Matriz de Rotação 9:
[[ 0.76359349  0.64401776  0.04654142]
 [-0.64420141  0.75493939  0.12276427]
 [ 0.04392642 -0.12372404  0.99134395]]

Matriz de Rotação 10:
[[ 0.16633729  0.98254084 -0.08333909]
 [-0.97114259  0.17788301  0.15887008]
 [ 0.17092095  0.05450812  0.98377583]]

Matriz de Rotação 11:
[[ 0.50393916  0.85980761 -0.08231764]
 [-0.85345898  0.51033493  0.10566945]
 [ 0.13286497  0.01700376  0.99098828]]

Matriz de Rotação 12:
[[ 0.91664789  0.39969426 -0.00106735]
 [-0.39958446  0.91645253  0.02114293]
 [ 0.00942889 -0.01895413  0.99977589]]

Matriz de Rotação 13:
[[ 0.37712958 -0.92319421 -0.07406568]
 [ 0.92474093  0.37091947  0.08528167]
 [-0.05125914 -0.1006538   0.99360018]]

Matriz de Rotação 14:
[[ 0.65620321 -0.75427988 -0.02142902]
 [ 0.75385812  0.65406186  0.06245807]
 [-0.03309496 -0.05713962  0.99781751]]

Matriz de Rotação 15:
[[ 0.72454101  0.68790687  0.04271363]
 [-0.68591695  0.71359983  0.14245425]
 [ 0.06751482 -0.13251195  0.98887933]]

Matriz de Rotação 16:
[[ 8.41220284e-04  9.99918326e-01  1.27528087e-02]
 [-9.97962558e-01  2.58500595e-05  6.38022900e-02]
 [ 6.37967493e-02 -1.27804974e-02  9.97881072e-01]]

Matriz de Rotação 17:
[[-0.01617598 -0.99451245 -0.10336016]
 [ 0.99980249 -0.01489454 -0.0131577 ]
 [ 0.011546   -0.10355258  0.99455696]]

```

## Vetores de translação
```python
1.  [-0.51390472, -3.61087759, 11.98349545] 
2.  [-2.23785966, -0.91020112, 11.98254531] 
3.  [-2.74120302,  1.27218519, 12.23502419] 
4.  [-1.8170356 ,  0.37274676, 11.85786959]
5.  [ 2.41180475, -4.171764  , 11.90631951]
6.  [-1.19673582, -4.17106584, 12.61140685] 
7.  [ 1.85675187, -4.07619415, 11.83062353] 
8.  [ 1.69711179, -4.28347655, 12.38334676] 
9.  [-3.36115948, -1.84006522, 12.48795394] 
10. [-3.01652001,  0.72076773, 12.66147845] 
11. [-3.45083683, -0.84847687, 12.65008913]
12. [-2.64590217, -2.58070564, 12.8343403 ]
13. [ 3.17631449, -4.17250226, 11.66669065]
14. [ 1.28179035, -4.54498845, 10.81781082]
15. [-4.32220073, -1.54420476, 11.41354967]
16. [-3.53420462,  2.45834165,  8.56083308]
17. [ 2.1943884 ,  0.49049849, 12.30880216]
```

# Vetor de distorção:
```python
[ 0.07726933 -0.43758116  0.00139022  0.00357039  0.58434254]

```

# 3.D: Utilizando uma câmera calibrada, obtenha imagens coloridas. Elaborar um programa com a função cv.undistort(), fazendo uso dos parâmetros decalibração obtidos desta câmera. Apresentar as imagens originais e as imagens corrigidas lado a lado.


In [ ]:
 pip install opencv-python

In [8]:
import cv2
import numpy as np
import os

camera_matrix = np.array([[1.13511501e+03, 0.00000000e+00, 7.77037877e+02],
                          [0.00000000e+00, 1.13837129e+03, 6.33562127e+02],
                          [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
dist_coeffs = np.array([0.07726933, -0.43758116, 0.00139022, 0.00357039, 0.58434254])


input_dir = '3C'
output_dir1 = '3D'
output_dir2 = 'fotos_beside'

if not os.path.exists(output_dir1):
    os.makedirs(output_dir1)

for filename in os.listdir(input_dir):
    if filename.endswith('.jpg'):
        filepath = os.path.join(input_dir, filename)

        img = cv2.imread(filepath)

        undistorted_img = cv2.undistort(img, camera_matrix, dist_coeffs)

        output_filepath = os.path.join(output_dir1, filename)

        cv2.imwrite(output_filepath, undistorted_img)

if not os.path.exists(output_dir2):
    os.makedirs(output_dir2)

for filename in os.listdir(input_dir):
    if filename.endswith('.jpg'):
        filepath1 = os.path.join(input_dir, filename)
        filepath2 = os.path.join(output_dir1, filename)

        img1 = cv2.imread(filepath1)
        img2 = cv2.imread(filepath2)

        if img1 is not None and img2 is not None:
            combined_img = np.hstack((img1, img2))

            output_filepath = os.path.join(output_dir2, filename)

            cv2.imwrite(output_filepath, combined_img)

print(f"Imagens salvas na pasta {output_dir2}.")


ImportError: libGL.so.1: cannot open shared object file: No such file or directory